### PR TITLE
Add nvrtc JNI binders.

### PR DESCRIPTION
**Pull request by nicblanc**
This is a first (and perfectible) version of the JNI binders for the nvidia runtime compiler for cuda. Let me know if you're interested, it allows to compile cuda code into ptx at runtime without calling  nvcc and can be used without any c++ compiler (at least it should), which is very useful if you do not want to install VS on windows ! 
You can use it as follow:

final CUprogram prog = new CUprogram();
final String src = ...;// cuda code
try {
	JNvrtc.nvrtcCreateProgram(prog, src, "programName", 0, null, null);
	final String[] options = new String[]{"--fmad=true", "--gpu-architecture=compute_52", "--device-as-default-execution-space", "--restrict"};
	JNvrtc.nvrtcCompileProgram(prog, options.length, options); 
	final String[] ptx = new String[1];
	JNvrtc.nvrtcGetPTX(prog, ptx);
	JNvrtc.nvrtcDestroyProgram(prog);
	final CUmodule module = new CUmodule();
	JNvrtc.cuModuleLoadDataEx(module, ptx[0]);
	final CUfunction function = new CUfunction();
	cuModuleGetFunction(function, module, "kernelName");
	// do what you want with it... 
} catch(CudaException ce){
    String[] log = new String[1];
    JNvrtc.nvrtcGetProgramLog(prog, log);
    System.out.println(log[0]);
}

### CODE REVIEW

**Comment by jcuda** [comment]
Wow, thank you, this is really a great contribution/idea! 

However, I'll likely not pull it in its current form, but rather use it as a "template" for an extension to support the nvrtc. I'm still reviewing it, but some of the reasons, from quickly skimming over it (roughly (!) sorted by severness) :

- File headers (I'm not sure whether you want an attribution, by name, or by linking to your GitHub page?)
- I'd likely not place it into the `driver` package, but a dedicated `nvrtc` one
- Some naming stuff. Although `nvrtcResult` should be called `NvrtcResult` in Java, I'd rather call it `nvrtcResult` - but not `CUNvrtcResult`. (The `CU` prefix that is used for the other classes stems from the fact that the CUDA driver structures are called *exactly like that*, e.g. `CUfunction`)
- I noticed your comment regarding `Java_jcuda_driver_JNvrtc_cuModuleLoadDataExNative` - calling this function from Java is indeed a bit fiddly, I'll think about a solution for that
- Regarding the JNI code, I think that some `ReleaseStringUTFChars` calls are missing, but I have just started looking at this, and will investigate it in more detail

But basically, I just tested it, with the ubiquitous "vector addition" example, and it worked smoothly! Further tests (e.g. with real headers and include names for `nvrtcCreateProgram`) will be necessary. I'll try to integrate these extensions ASAP. 

Thanks again! 

(This might help to get rid of the `preparePtxFile` stuff that I used in the samples to create the PTX at runtime. I wonder how I could overlook the RTC when it slipped into CUDA 7.0 - it's certainly a feature that is worth integrating!)

**Comment by nicblanc** [comment]
Thanks for the comments !!
I did not expect you to merge this (mainly because the code is a little bit messy) but I created the pull request so that you can take a look at the work I've done.

I'll try to modify the code in order to take care of your comments as soon as possible.

Another thing, I am not very familiar with cmake, I wrote something in the CMakeLists.txt that seems to work on windows but I don't think that is the right way to link the nvrtc library. Maybe you can look into it and tell me how to write something better.

**Comment by jcuda** [comment]
The CMake files and the POMs looked OK at a first glance - basically, the nvrtc part will follow the same "pattern" as the Runtime/Driver parts. Of course, there are a few lines of boilerplate code for the native libraries in the POM, but this should still be fine. 

I haven't looked in detail at the status after your last commit, but just to avoid misunderstandings: When I said that I would not pack it into the `driver` package, this really referred to the java package `jcuda.driver`. As the nvrtc is part of "core" CUDA, at the same level of integration as the core Runtime/Driver API, I think that the pattern

    Github project    Java package     JNI part
    jcuda             jcuda.driver     JCudaDriverJNI
    jcuda             jcuda.runtime    JCudaRuntimeJNI
    jcuda             jcuda.nvrtc      JNvrtcJNI

makes sense.

--- 

At least, this is a clear and somewhat reasonable structure - although the separation between `JCudaRuntimeJNI` and `JCudaDriverJNI` is mainly due to historical reasons (from the earliest CUDA versions, <3.0). One could consider combining *all* JNI-parts for the `jcuda` project. And this would be reasonable as well, and might even simplify some things (e.g. there would only be *one* native library for the core jcuda part). But I'm aftraid that it might become a bit too large and potentially messy, so I'm hesitant to mix them together unless there is a compelling reason to do so.

**Comment by nicblanc** [comment]
Indeed I misunderstood you, I created another project for nvrtc like you did for cublas and the other libraries. I'll put back the code in JCuda and change the java package !

**Comment by jcuda** [comment]
You probably don't have to invest soo many efforts here, I'll try to tackle this today and tomorrow to see how this (including things like the ´cuModuleLoadDataEx` issue) can be solved.

**Comment by nicblanc** [comment]
Of course, keep me posted ! 
I just wanted to have something functional for my personal use ;)

**Comment by jcuda** [comment]
So the first version of JNvrtc has been added here: https://github.com/jcuda/jcuda/commit/b8d1a4aee3c338d1a48ae4228f18b115f210496a

(With minor updates in 
https://github.com/jcuda/jcuda-main/commit/89e4d4f32c6988c06a4d7d14cdb529876aeed20f and
https://github.com/jcuda/jcuda-common/commit/45087f914f990739e6e621e423f1889c53d5af31 )

I also tried to simplify the `cuModuleLoadData*` parts, in https://github.com/jcuda/jcuda/commit/79513f213305383696ea1bce627bcd5c1769d83f . As indicated by the comments in the native method: The behavior of the original CUDA `cuModuleLoadDataEx` function is a bit odd. Additionally, the handling of the `JITOptions` is a bit fiddly on Java side. However, the most general case of just loading a PTX from a string should be far easier now.  

I'll just dump the first sample that I would upload to the website here, for the case that someone wants to try it out: 

```
/*
 * JCuda - Java bindings for NVIDIA CUDA driver and runtime API
 * http://www.jcuda.org
 *
 * Copyright 2016 Marco Hutter - http://www.jcuda.org
 */

package jcuda.nvrtc.samples;

import static jcuda.driver.JCudaDriver.cuCtxCreate;
import static jcuda.driver.JCudaDriver.cuCtxSynchronize;
import static jcuda.driver.JCudaDriver.cuDeviceGet;
import static jcuda.driver.JCudaDriver.cuInit;
import static jcuda.driver.JCudaDriver.cuLaunchKernel;
import static jcuda.driver.JCudaDriver.cuMemAlloc;
import static jcuda.driver.JCudaDriver.cuMemFree;
import static jcuda.driver.JCudaDriver.cuMemcpyDtoH;
import static jcuda.driver.JCudaDriver.cuMemcpyHtoD;
import static jcuda.driver.JCudaDriver.cuModuleGetFunction;
import static jcuda.driver.JCudaDriver.cuModuleLoadData;
import static jcuda.nvrtc.JNvrtc.nvrtcCompileProgram;
import static jcuda.nvrtc.JNvrtc.nvrtcCreateProgram;
import static jcuda.nvrtc.JNvrtc.nvrtcDestroyProgram;
import static jcuda.nvrtc.JNvrtc.nvrtcGetPTX;
import static jcuda.nvrtc.JNvrtc.nvrtcGetProgramLog;
import jcuda.Pointer;
import jcuda.Sizeof;
import jcuda.driver.CUcontext;
import jcuda.driver.CUdevice;
import jcuda.driver.CUdeviceptr;
import jcuda.driver.CUfunction;
import jcuda.driver.CUmodule;
import jcuda.driver.JCudaDriver;
import jcuda.nvrtc.JNvrtc;
import jcuda.nvrtc.nvrtcProgram;

/**
 * An example showing how to use the NVRTC (NVIDIA Runtime Compiler) API
 * to compile CUDA kernel code at runtime.
 */
public class JNvrtcVectorAddSample
{
    /**
     * The source code of the program that will be compiled at runtime:
     * A simple vector addition kernel. 
     * 
     * Note: The function should be declared as  
     * extern "C"
     * to make sure that it can be found under the given name.
     */
    private static String programSourceCode = 
        "extern \"C\"" + "\n" +
        "__global__ void add(int n, float *a, float *b, float *sum)" + "\n" +
        "{" + "\n" +
        "    int i = blockIdx.x * blockDim.x + threadIdx.x;" + "\n" +
        "    if (i<n)" + "\n" +
        "    {" + "\n" +
        "        sum[i] = a[i] + b[i];" + "\n" +
        "    }" + "\n" +
        "}" + "\n";
    
    /**
     * Entry point of this sample
     * 
     * @param args Not used
     */
    public static void main(String[] args)
    {
        // Enable exceptions and omit all subsequent error checks
        JCudaDriver.setExceptionsEnabled(true);
        JNvrtc.setExceptionsEnabled(true);

        // Initialize the driver and create a context for the first device.
        cuInit(0);
        CUdevice device = new CUdevice();
        cuDeviceGet(device, 0);
        CUcontext context = new CUcontext();
        cuCtxCreate(context, 0, device);

        
        
        // Use the NVRTC to create a program by compiling the source code
        nvrtcProgram program = new nvrtcProgram();
        nvrtcCreateProgram(
            program, programSourceCode, null, 0, null, null);
        nvrtcCompileProgram(program, 0, null);
        
        // Print the compilation log (for the case there are any warnings)
        String programLog[] = new String[1];
        nvrtcGetProgramLog(program, programLog);
        System.out.println("Program compilation log:\n" + programLog[0]);        
        
        // Obtain the PTX ("CUDA Assembler") code of the compiled program
        String[] ptx = new String[1];
        nvrtcGetPTX(program, ptx);
        nvrtcDestroyProgram(program);

        // Create a CUDA module from the PTX code
        CUmodule module = new CUmodule();
        cuModuleLoadData(module, ptx[0]);

        // Obtain the function pointer to the "add" function from the module
        CUfunction function = new CUfunction();
        cuModuleGetFunction(function, module, "add");


        
        // Continue with some basic setup for the vector addition itself:

        // Allocate and fill the host input data
        int numElements = 256 * 100;
        float hostInputA[] = new float[numElements];
        float hostInputB[] = new float[numElements];
        for(int i = 0; i < numElements; i++)
        {
            hostInputA[i] = (float)i;
            hostInputB[i] = (float)i;
        }

        // Allocate the device input data, and copy the
        // host input data to the device
        CUdeviceptr deviceInputA = new CUdeviceptr();
        cuMemAlloc(deviceInputA, numElements * Sizeof.FLOAT);
        cuMemcpyHtoD(deviceInputA, Pointer.to(hostInputA),
            numElements * Sizeof.FLOAT);
        CUdeviceptr deviceInputB = new CUdeviceptr();
        cuMemAlloc(deviceInputB, numElements * Sizeof.FLOAT);
        cuMemcpyHtoD(deviceInputB, Pointer.to(hostInputB),
            numElements * Sizeof.FLOAT);

        // Allocate device output memory
        CUdeviceptr deviceOutput = new CUdeviceptr();
        cuMemAlloc(deviceOutput, numElements * Sizeof.FLOAT);

        // Set up the kernel parameters: A pointer to an array
        // of pointers which point to the actual values.
        Pointer kernelParameters = Pointer.to(
            Pointer.to(new int[]{numElements}),
            Pointer.to(deviceInputA),
            Pointer.to(deviceInputB),
            Pointer.to(deviceOutput)
        );

        
        
        // Call the kernel function, which was obtained from the
        // module that was compiled at runtime
        int blockSizeX = 256;
        int gridSizeX = (numElements + blockSizeX - 1) / blockSizeX;
        cuLaunchKernel(function,
            gridSizeX,  1, 1,      // Grid dimension
            blockSizeX, 1, 1,      // Block dimension
            0, null,               // Shared memory size and stream
            kernelParameters, null // Kernel- and extra parameters
        );
        cuCtxSynchronize();

        // Allocate host output memory and copy the device output
        // to the host.
        float hostOutput[] = new float[numElements];
        cuMemcpyDtoH(Pointer.to(hostOutput), deviceOutput,
            numElements * Sizeof.FLOAT);

        // Verify the result
        boolean passed = true;
        for(int i = 0; i < numElements; i++)
        {
            float expected = i+i;
            if (Math.abs(hostOutput[i] - expected) > 1e-5)
            {
                System.out.println(
                    "At index "+i+ " found "+hostOutput[i]+
                    " but expected "+expected);
                passed = false;
                break;
            }
        }
        System.out.println("Test "+(passed?"PASSED":"FAILED"));

        // Clean up.
        cuMemFree(deviceInputA);
        cuMemFree(deviceInputB);
        cuMemFree(deviceOutput);
        
    }
}

```

Further tests (e.g. with additional header files and options) will be added later.

@nicblanc Again, if you would like any attribution (by name or link)m then I'd add it. Otherwise, you'll at least receive an implicit "honorable mention" via a link to this issue in the "News" on the website, when the JNvrtc part becomes part of a release ;-)

**Comment by jcuda** [comment]
I just noticed your last commit, related to some locale - may I ask what this is about? 
(I'm always insecure when something touches potential unicode/encoding problems. That's always délicat ... )

**Comment by nicblanc** [comment]
Great work !!

About the locale issue, I built my branch of JCuda on ubuntu 14.04 in order to test nvrtc on it, and it seems that there is a bug. 

In my cuda code, I have a marcro `#define DBL_EPSILON 2.2204460492503131e-16 ` and after compiling with nvrtc the value of my macro became 2. So I tried to define a local variable in the code `double dbl = 2.2204460492503131e-16`, here again the value was still 2.
I had the same problem with all my static  floating point variables. 
But when I declared, for instance pi, like `double pi = 3141592653589793 * 10e-16`, the value was ok. So I suspected that there was a problem with the locale, which is in french on the computer. 

In french, we use "," instead of "." for representing floating point values (in general, not in the code), I think there is an issue occurring with nvrtc while parsing the code with the french locale. I set the locale `LC_ALL=C` in eclipse and re-run my tests and then it worked. 

Maybe the problem comes from Nvidia, maybe it comes from my code, I really don't know, so I force the locale in my c++ code in order to be sure that it will work with any locale. It worked for me.

I'll try your version to see if I have the same problem. But if the problem comes from Nvidia, I think we should tell them, it is a pretty serious issue.

About the attribution, any form you seem appropriate will do, I already really glad that you will mention my name somewhere :)

**Comment by jcuda** [comment]
Thanks. This locale issue is strange indeed. A quick websearch did not bring any obvious results, which is even more irritating. 

Maybe I'm overly careful here, but I noticed that you used plain `GetStringUTFChars` calls in your native code, and I had to revise why I used these odd [`convertString`](https://github.com/jcuda/jcuda-common/blob/master/JCudaCommonJNI/src/JNIUtils.cpp#L416) contortions. Now I added a comment, pointing to https://web.archive.org/web/20120626012047/http://java.sun.com/docs/books/jni/html/pitfalls.html , chapter 10.10 (the `convertString` is basically the `JNU_GetStringNativeChars` that is mentioned there) - although there may still be caveats that I did not consider: The conversion between Java Unicode Strings and native strings is always difficult, and the unicode/utf8-support in C is a bit brittle. Most C-APIs don't say anything about encodings, and likely expect plain ASCII. At least, I guess that the NVIDIA compiler would bail out when it encountered a 变量 somewhere, regardless of the encoding. It shouldn't bail out for `2.22....`, though...

**Comment by nicblanc** [comment]
Hi Marco, it seems that the pom in your jcuda-main has a small typo here: https://github.com/jcuda/jcuda-main/blob/master/pom.xml#L91

It should be JNvrtc-native instead of JCudaDriver-native.
`mvn clean install` is copying the JCudaDriver dll into the JNvrtc dll, resulting unstatified link error if you want to use the dlls in the jcuda-main/target repository.

**Comment by jcuda** [comment]
Sure, thanks (the boon and bane of copy and paste - I somehow expected something like this...). I'll fix it soon. Did everything else work as expected after adjusting this ID? 
(If so, I'd close this request)

**Comment by jcuda** [comment]
I assume that this request itself can be closed now. The tasks to add further tests and samples is still on my TODO list, and if there are problems with the current implementation, they can be handled with the issue tracker.

Thanks again for your inputs!

**Pull request closed without merging**
