### PR TITLE
cuMemPool functions

### PR DESCRIPTION
**Pull request by iimanii**
cuMemAllocAsync
cuMemAllocFromPoolAsync
cuMemPoolCreate
cuMemPoolDestroy
cuMemPoolTrimTo

was hoping you added those for a while now

### CODE REVIEW

**Comment by jcuda** [comment]
I had seen the memory pool functions in one of the previous releases. I did not add support for them, because I didn't see a use-case for a subset of the functions (like the ones that are added here), _without_ adding support for _all_ functions. And the latter refers to stuff like `cuMemPoolImportFromShareableHandle` and others that are missing here.

So... I can merge that 🤷‍♂️ (even though you may have noticed that I'm not really making any regular updates any more - time is money, and I don't have enough of both of them). But I'd at least be curious what a _basic_ usage pattern of these functions could look like. (I mean, there are _zero_ examples using a `CUmemoryPool` in https://github.com/NVIDIA/CUDALibrarySamples , so... it doesn't seem to be the most important functionality after all). 

(If such an example exists, then it could eventually go into https://github.com/jcuda/jcuda-samples , but right now, I'm just curious...)

**Comment by iimanii** [comment]
well atleast this one `cuMemAllocAsync` is pretty important .. does make things go alot faster when using streams. Creating and releasing alot of memory is very costly, I thought the mempool stuff would make things go faster, which it does but is as good as using the AllocAsync, as far as my testing went

I was going to add all the other mempool functions, but some of them are just so troublesome, specifically the ones that required getting and setting attributes

**Comment by jcuda** [comment]
I see, the `cuMemAllocAsync`/`cuMemFreeAsync` are actually not pool-specific 
(And I thought that I had added them once, but may have missed them)
So yes, these functions could reasonably be part of the API. 

Do you think that the other functions (that really _are_ pool-related) make sense in isolation? I had looked at things like the `CUmemPoolProps`, which contain some obscure parameters and nested, untyped stuff (WTF is `win32SecurityAttributes`!?), and I wasn't even sure whether it made sense to try and port that attribute- and handle-handling to Java. So I just omitted that. 

(NVIDIA is worth 3 TRILLION dollars. I'm doing all this in my spare time. Why?)

**Comment by iimanii** [comment]
I'm guessing the other functions [the ones i didn't add in this PR] might be used when dealing with a large grid of GPUs or something, and at that point if someone wants those functions they can just create another PR and add them

I actually had them in initially but they kept giving errors when testing so I removed them

**Comment by jcuda** [comment]
> if someone wants those functions they can just create another PR and add them

That's the spirit 🙂 

I'll have a closer look at the changes, maybe do some _very_ basic test, and probably merge them later.

As I said: I'm not really doing any regular releases any more. But when there is such a change, it could be a reason to at least _consider_ releasing new _binaries_ (even though the API might have changed). We're currently at CUDA 12.6, and the last release was with CUDA 12, so hopfeully, that should still largely be compatible 🤞 

An open question would be if @blueberry and @corepointer would still be willing to help out with the Linux binaries. I know, it has been a while (and will likely still take a few days until things are prepared for a new release). But it wouldn't make much sense to create a Maven release that only contains the Windows binaries....

**Comment by blueberry** [comment]
Of course, but as far as I remember, my binaries are only compatible with new-ish Linux because I'm on Arch Linux...

**Comment by jcuda** [comment]
@blueberry Great. Yes, I remember that eventually @corepointer provided the last binaries (compiled with an older GLIBC version or so). I could imagine that your GLIBC version, which was "too new" in the last release, might now be more common, but ... maybe Arch Linux is doing something like ~"always updating to the latest version" or so, and in general, it seems to be a good strategy to ~"always compile against the oldest version that works". 

A few things remain to be sorted out, and it will take a few days until I can look into this and prepare a new release, but it's good to know that such a release could still include Linux binaries (even when the GLIBC version question is up for debate...)

**Comment by iimanii** [comment]
I compiled the libraries on ubuntu 20 .. would gladly share those just need to know where/how

as for testing I had this code to make sure functions are being called without issues .. putting it here if its of any use

`package CudaTests;

import jcuda.Pointer;
import jcuda.driver.CUcontext;
import jcuda.driver.CUdevice;
import jcuda.driver.CUdevice_attribute;
import jcuda.driver.CUdeviceptr;
import jcuda.driver.CUmemAllocationHandleType;
import jcuda.driver.CUmemAllocationType;
import jcuda.driver.CUmemLocation;
import jcuda.driver.CUmemLocationType;
import jcuda.driver.CUmemPoolProps;
import jcuda.driver.CUmemoryPool;
import jcuda.driver.CUstream;
import jcuda.driver.JCudaDriver;
import org.fjnn.cuda.CudaUtil;

public class JCudaDriverMemoryPoolTest {
    
    public static void main(String[] args) {
        // Initialize the JCuda driver
        JCudaDriver.setExceptionsEnabled(true);
        JCudaDriver.cuInit(0);

        // Create a CUcontext and CUdevice
        CUdevice device = new CUdevice();
        JCudaDriver.cuDeviceGet(device, 0);

        CUcontext context = new CUcontext();
        JCudaDriver.cuCtxCreate(context, 0, device);
        
        // Get the number of CUDA devices
        int[] deviceCount = new int[1];
        JCudaDriver.cuDeviceGetCount(deviceCount);
        System.out.println("Number of devices: " + deviceCount[0]);

        // Check if the device supports memory pools
        int[] memPoolSupported = new int[1];
        JCudaDriver.cuDeviceGetAttribute(memPoolSupported, CUdevice_attribute.CU_DEVICE_ATTRIBUTE_MEMORY_POOLS_SUPPORTED, device);

        if (memPoolSupported[0] != 0)
            System.out.println("Device " + 0 + " supports memory pools.");
        else
            System.out.println("Device " + 0 + " does NOT support memory pools.");
        
        // Test cuMemPoolCreate
        System.out.println("Testing cuMemPoolCreate...");
        CUmemPoolProps poolProps = new CUmemPoolProps();
        poolProps.allocType = CUmemAllocationType.CU_MEM_ALLOCATION_TYPE_PINNED;
        poolProps.handleTypes = CUmemAllocationHandleType.CU_MEM_HANDLE_TYPE_NONE;
        poolProps.location = new CUmemLocation();
        poolProps.location.id = 0;
        poolProps.location.type = CUmemLocationType.CU_MEM_LOCATION_TYPE_DEVICE;
        poolProps.win32SecurityAttributes = new Pointer();
        
        CUmemoryPool pool = new CUmemoryPool();
        JCudaDriver.cuMemPoolCreate(pool, poolProps);
        System.out.println("Memory pool created");

        // Test cuMemAllocFromPoolAsync
        System.out.println("Testing cuMemAllocFromPoolAsync...");
        CUdeviceptr dptr = new CUdeviceptr();
        CUstream stream = new CUstream();
        JCudaDriver.cuStreamCreate(stream, 0);
        JCudaDriver.cuMemAllocFromPoolAsync(dptr, 1024, pool, stream);
        JCudaDriver.cuMemsetD8Async(dptr, (byte)1, 1024, stream);
        System.out.println("Memory allocated from pool");
        
        byte[] value = CudaUtil.fromGPUAsync(dptr, 1024, stream);
        
        for(int i=0; i < 20; i++) {
            System.out.print(value[i]);
        }
        System.out.println();

        // Test cuMemFreeAsync
        System.out.println("Testing cuMemFreeAsync...");
        JCudaDriver.cuMemFreeAsync(dptr, stream);
        System.out.println("Memory freed asynchronously");
        
        // Test cuMemPoolTrimTo
        System.out.println("Testing cuMemPoolTrimTo...");
        JCudaDriver.cuMemPoolTrimTo(pool, 512);
        System.out.println("Memory pool trimmed");

        // Test cuMemPoolDestroy
        System.out.println("Testing cuMemPoolDestroy...");
        JCudaDriver.cuMemPoolDestroy(pool);
        System.out.println("Memory pool destroyed");

        // Clean up
        JCudaDriver.cuStreamDestroy(stream);
        JCudaDriver.cuCtxDestroy(context);

        System.out.println("Test completed successfully.");
    }
}
`

**Comment by jcuda** [comment]
Thanks @iimanii , I'll try to take a look soon. 

Do you happen to know which GLIBC version your build is using? There had been some issues, around https://github.com/jcuda/jcuda-main/issues/51 , so I'll usually try to ~"use the lowest version that works"...

**Comment by iimanii** [comment]
(Ubuntu GLIBC 2.31-0ubuntu9.16) 2.31

**Comment by jcuda** [comment]
This is still in the pipeline, but has not been forgotten.

**Comment by jcuda** [comment]
Thanks again @iimanii : I tried it out locally, and the test seems to work, so I merged it.

I'll prepare a new release, but before that, I'll have a _quick_ look at the latest cuDNN version: The last version that I used previously was 8.x, and the latest one is 9.x. Although I'm no longer doing "real updates" for the whole CUDA API, I'll at least have a look whether there have been any simple changes in the cuDNN API (like renamed functions, or a parameter added here or there). 

After that, the process for the release involves some manual steps, but is basically...

- update all version numbers in the POMs and CMake files
- compile the whole thing to create the Windows DLLs
- create a tag `version-12.6.0-RC00`
- Ask someone to compile and provide the Linux binaries based on this state
  - You mentioned that you already compiled them. But depending on whether there are any other changes, they may have to be compiled from _exactly_ this tag to actually work. The way how they are provided usually is to compile the native (`.so`) files, and then run `mvn clean package` to create the `/target...` directories. These will contain a bunch of `jcuda-natives-12.6.0-linux-x86_64.jar` files. This set of JAR files (for each JCuda library) are what I need for the release.
- Wrap duct tape around the whole thing (signing, packaging, uploading to Sonatype) and release it to Maven Central

I'll drop a note where when the tag is created and the release is ready to be built.

<sub>(Don't hold your breath - there's a certain tension between "working _for free_ for a there _trillion(!)_ dollar company" and "having to pay rent". But I'll _try_ to get it done. Users of JCuda shouldn't suffer toooo much from the stinginess of NVIDIA...)</sub>

**Comment by iimanii** [comment]
great .. will compile once everything is ready

**Pull request merged**
